### ISSUE TITLE
node app.js report error

### ISSUE THREAD

**Issue by lifangwang** [MennaDarwish/DSP#79]
I install express and input following in windows command line:
node app,js

some error reporting  as fllowing, I want to know how to fix this problem?

<pre>
D:\wlf_code\jscode\DSP-master> node app.js
events.js:397
EventEmitter.listenerCount = function(emitter, type) {
                                     ^

RangeError: Maximum call stack size exceeded
    at Function.EventEmitter.listenerCount (events.js:397:38)
    at Log.listenerCount (D:\wlf_code\jscode\DSP-master\node_modules\elasticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (D:\wlf_code\jscode\DSP-master\node_modules\elasticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (D:\wlf_code\jscode\DSP-master\node_modules\elasticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (D:\wlf_code\jscode\DSP-master\node_modules\elasticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (D:\wlf_code\jscode\DSP-master\node_modules\elasticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (D:\wlf_code\jscode\DSP-master\node_modules\elasticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (D:\wlf_code\jscode\DSP-master\node_modules\elasticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (D:\wlf_code\jscode\DSP-master\node_modules\elasticsearch\src\lib\log.js:68:25)
</pre>

**Comment by GavinGuo000** [comment]
node版本问题，装个0.10的试试
